#KARPENTER 1.8.0 + VERSION REQUIRED
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: <YOUR-EC2-NODE-CLASS-NAME-HERE>
spec:
  role: "<YOUR-KARPENTER-NODE-ROLE-ARN-HERE>"

  tags:
    Name: "STAG-KARPENTER-NODE" #NAME-OF-YOUR-NEWLY-CREATED-NODE
    Environment: "staging"
    Owner: "aaqib"
    Provisioner: "karpenter"
    karpenter.sh/discovery: "<YOUR-KUBERNETES-CLUSTER-HERE>"  

  amiFamily: AL2023
  amiSelectorTerms:
    - id: "ami-0facba1ae974a803d"

  subnetSelectorTerms:
    - id: "<YOUR-SUBNET-ID-HERE>"

  securityGroupSelectorTerms:
    - id: "<YOUR-SECURITY-GROUP-ID-HERE>"

  blockDeviceMappings:
    - deviceName: "/dev/xvda"
      rootVolume: true
      ebs:
        volumeSize: 50Gi
        volumeType: gp2
        encrypted: true
        deleteOnTermination: true

  metadataOptions:
    httpEndpoint: enabled
    httpTokens: required
    httpPutResponseHopLimit: 2
    httpProtocolIPv6: disabled
